stages:
  - test
  - build
  - release

test:
  stage: test
  image: docker:latest
  services:
    - docker:dind

  before_script:
    - apk add --update build-base python3-dev py-pip
    - apk add libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose

  script:
    - export
    - ln -s docker/environments/ci.env .env
    - docker-compose -f docker-compose.yml -f docker/compose/ci.yml up -d
    - docker-compose exec -T web pytest

  only:
    - develop
    - branches

pages:
  stage: release
  image: python:3.8-buster
  before_script:
    - pip install mkdocs
    - pip install mkdocs-material

  script:
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - master
