version: '2.2'

services:
  geth-dev:
    image: ethereum/client-go:latest
    volumes:
      - "./docker/volumes/geth/chain/${HUB20_WEB3_NETWORK}:/root/.ethereum"
    command:
      "--rpc --rpcaddr 0.0.0.0 --ws --wsaddr 0.0.0.0 --nousb ${HUB20_GETH_EXTRA_OPTS}"

  db:
    image: postgres
    restart: always
    volumes:
      - "./docker/volumes/database/${HUB20_DATABASE_NAME}:/var/lib/postgresql/data"

    environment:
      POSTGRES_DB: ${HUB20_DATABASE_NAME}
      POSTGRES_USER: ${HUB20_DATABASE_USER}
      POSTGRES_PASSWORD: ${HUB20_DATABASE_PASSWORD}

  # Redis for cache and session
  redis:
    image: redis:latest

  # Web API
  web:
    stdin_open: true
    tty: true
    command: >
      /bin/bash -c "
        while ! nc -w 1 -z db 5432; do sleep 0.5; done;
        while ! nc -w 1 -z redis 6379; do sleep 0.5; done;
        django-admin migrate;
        django-admin runserver 0.0.0.0:8000
      "

    image: mushroomlabs/hub20
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

    env_file:
      - ./.env

  # Celery app
  celery:
    stdin_open: true
    tty: true
    command: >
      /bin/bash -c "
        while ! nc -w 1 -z db 5432; do sleep 0.5; done;
        while ! nc -w 1 -z redis 6379; do sleep 0.5; done;
        celery worker -A hub20.api -l info
      "

    image: mushroomlabs/hub20
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

    env_file:
      - ./.env

  # Celery beat (periodic tasks)
  celery_beat:
    command: >
      /bin/bash -c "
        mkdir -p ${HUB20_DATA_FOLDER}/celery
        while ! nc -w 1 -z db 5432; do sleep 0.5; done;
        while ! nc -w 1 -z redis 6379; do sleep 0.5; done;
        celery beat -A hub20.api -l info -s ${HUB20_DATA_FOLDER}/celery/celerybeat-schedule.db --pidfile=${HUB20_DATA_FOLDER}/celery/celerybeat.pid
      "
    image: mushroomlabs/hub20
    build: .
    volumes:
      - .:/app
      - "./docker/volumes/celery:${HUB20_DATA_FOLDER}/celery"
    depends_on:
      - db
      - redis

    env_file:
      - ./.env

  # Background command to synchonize blockchain
  job_sync_blockchain:
    command: >
      /bin/bash -c "
        while ! nc -w 1 -z db 5432; do sleep 0.5; done;
        while ! nc -w 1 -z redis 6379; do sleep 0.5; done;
        django-admin sync_blockchain
      "

    image: mushroomlabs/hub20
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

    env_file:
      - ./.env


  # Background command to synchonize raiden
  job_sync_raiden:
    command: >
      /bin/bash -c "
        while ! nc -w 1 -z db 5432; do sleep 0.5; done;
        while ! nc -w 1 -z redis 6379; do sleep 0.5; done;
        django-admin sync_raiden
      "

    image: mushroomlabs/hub20
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

    env_file:
      - ./.env

  # Background command to track payments
  job_track_payments:
    command: >
      /bin/bash -c "
        while ! nc -w 1 -z db 5432; do sleep 0.5; done;
        while ! nc -w 1 -z redis 6379; do sleep 0.5; done;
        django-admin track_pending_payments
      "

    image: mushroomlabs/hub20
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

    env_file:
      - ./.env
