version: '3.4'

x-backend: &hub20_backend
  image: "hub20_backend:${TAG:-latest}"
  build:
    context: ./backend
  depends_on:
    redis:
      condition: service_healthy
    db:
      condition: service_healthy

services:
  db:
    image: postgres:latest
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      retries: 5
    restart: unless-stopped

  # Redis for cache, session engine, celery and channels transport
  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: unless-stopped

  # Admin Site
  admin:
    <<: *hub20_backend

    command: >
      /bin/bash -c "
        django-admin collectstatic --noinput
        uvicorn hub20.admin.asgi:application --port 80 --host 0.0.0.0 --root-path="/admin" --reload --reload-dir /app/hub20
      "
    depends_on:
      - db
      - redis
    environment:
      HUB20_URLCONF_MODULE: hub20.admin.urls

  # Web API
  web:
    <<: *hub20_backend

    command: >
      /bin/bash -c "
        django-admin migrate;
        django-admin collectstatic --noinput
        uvicorn hub20.api.asgi:application --port 80 --host 0.0.0.0 --root-path="/api" --reload --reload-dir /app/hub20
      "
    depends_on:
      - db
      - redis

  # Celery app
  celery:
    <<: *hub20_backend

    command: celery -A hub20.api worker -l info
    depends_on:
      - db
      - redis
    environment:
      COLUMNS: 80

  # Celery beat (periodic tasks)
  celery_beat:
    <<: *hub20_backend

    command: >
      /bin/bash -c "
        mkdir -p ${HUB20_DATA_FOLDER}/celery;
        celery -A hub20.api beat -l info -s ${HUB20_DATA_FOLDER}/celery/celerybeat-schedule.db --pidfile=${HUB20_DATA_FOLDER}/celery/celerybeat.pid
      "
    depends_on:
      - db
      - redis

  # Run raiden via django-admin command
  raiden:
    <<: *hub20_backend

    command: django-admin run_raiden
    depends_on:
      - db
      - redis

  # Background command to listen to blockchain and raiden events
  job_listen_events:
    <<: *hub20_backend

    command: django-admin run_event_listeners
    depends_on:
      - db
      - redis

  # Background command to listen to blockchain and raiden events
  job_listen_raiden:
    <<: *hub20_backend

    command: django-admin sync_raiden
    depends_on:
      - db
      - redis
