version: '2.2'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - "./docker/volumes/database/${HUB20_DATABASE_NAME}:/var/lib/postgresql/data"

    environment:
      POSTGRES_DB: ${HUB20_DATABASE_NAME}
      POSTGRES_USER: ${HUB20_DATABASE_USER}
      POSTGRES_PASSWORD: ${HUB20_DATABASE_PASSWORD}

  # Redis for cache and session
  redis:
    image: redis:latest

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/volumes/media/hub20:/var/www/html/hub20
    depends_on:
      - web

  # Web API
  web:
    stdin_open: true
    tty: true
    command: >
      /bin/bash -c "
        while ! nc -w 1 -z db 5432; do sleep 0.5; done;
        while ! nc -w 1 -z redis 6379; do sleep 0.5; done;
        django-admin migrate;
        django-admin collectstatic --noinput
        uvicorn hub20.api.routing:application --port 8000 --host 0.0.0.0 --reload
      "

    image: mushroomlabs/hub20
    build: .
    volumes:
      - .:/app
      - ./docker/volumes/media/hub20/static:${HUB20_STATIC_ROOT:-/app/hub20/static}
    depends_on:
      - db
      - redis

    env_file:
      - ./.env

  # Celery app
  celery:
    stdin_open: true
    tty: true
    restart: always
    command: celery worker -A hub20.api -l info

    image: mushroomlabs/hub20
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      COLUMNS: 80
    env_file:
      - ./.env

  # Celery beat (periodic tasks)
  celery_beat:
    command: >
      /bin/bash -c "
        mkdir -p ${HUB20_DATA_FOLDER}/celery
        rm ${HUB20_DATA_FOLDER}/celery/celerybeat.pid || true
        while ! nc -w 1 -z db 5432; do sleep 0.5; done;
        while ! nc -w 1 -z redis 6379; do sleep 0.5; done;
        celery beat -A hub20.api -l info -s ${HUB20_DATA_FOLDER}/celery/celerybeat-schedule.db --pidfile=${HUB20_DATA_FOLDER}/celery/celerybeat.pid
      "
    image: mushroomlabs/hub20
    build: .
    volumes:
      - .:/app
      - "./docker/volumes/celery:${HUB20_DATA_FOLDER}/celery"

    depends_on:
      - db
      - redis

    env_file:
      - ./.env

  # Background command to synchonize blockchain
  job_sync_blockchain:
    stdin_open: true
    tty: true
    restart: always
    command: >
      /bin/bash -c "
        while ! nc -w 1 -z db 5432; do sleep 0.5; done;
        while ! nc -w 1 -z redis 6379; do sleep 0.5; done;
        django-admin sync_blockchain
      "

    image: mushroomlabs/hub20
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

    env_file:
      - ./.env

  # Background command to synchonize raiden
  job_sync_raiden:
    stdin_open: true
    tty: true
    restart: always
    command: >
      /bin/bash -c "
        while ! nc -w 1 -z db 5432; do sleep 0.5; done;
        while ! nc -w 1 -z redis 6379; do sleep 0.5; done;
        django-admin sync_raiden
      "

    image: mushroomlabs/hub20
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

    env_file:
      - ./.env

  # Background command to track payments
  job_track_payments:
    stdin_open: true
    tty: true
    restart: always
    command: >
      /bin/bash -c "
        while ! nc -w 1 -z db 5432; do sleep 0.5; done;
        while ! nc -w 1 -z redis 6379; do sleep 0.5; done;
        django-admin track_pending_payments
      "

    image: mushroomlabs/hub20
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

    env_file:
      - ./.env
