version: '2'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${HUB20_DATABASE_NAME}
      POSTGRES_USER: ${HUB20_DATABASE_USER}
      POSTGRES_PASSWORD: ${HUB20_DATABASE_PASSWORD}
    ports:
      - "${HUB20_DATABASE_PORT}:5432"
    volumes:
      - ./docker/volumes/database:/var/lib/postgresql/data

  # Redis for cache and session
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
