site_name: Hub20
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Ubuntu
    code: Ubuntu Mono
  language: en
repo_name: mushroomlabs/hub20
repo_url: https://github.com/mushroomlabs/hub20
